name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  ci_checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      #  Install Playwright browser for Vitest
      - name: Install Playwright browser
        run: npx playwright install --with-deps
      - name: Check style
        run: npm run check

      # API Test
      - name: Test
        run: npm run test

      # E2E Test
      - name: E2E Test
        run: npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  # deploy:
  #   needs: [ci_checks]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v6
  #     - uses: actions/setup-node@v6.3.0
  #       with:
  #         node-version: "24"
  #     - run: npm ci
  #     - name: Build
  #       run: npm run build
  #     - name: Install Playwright Browsers
  #       run: npx playwright install --with-deps
  #     - name: Run Playwright tests
  #       run: npm run test:e2e
  #     - uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: playwright-report
  #         path: playwright-report/
  #         retention-days: 30
